/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jav.deadlock;

import org.junit.Test;

import jav.deadlock.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
