/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javanullpointer;

import org.checkerframework.checker.nullness.qual.NonNull;

public class App {
    public static void main(String[] args) {
        @NonNull String s = null;
    }
}
