/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jav.deadlock;

public class App {

    static Object lock1 = new Object();
    static Object lock2 = new Object();
    public static void main(String[] args) {
        var t1 = new Thread(new Runnable() {
            public void run() {
                synchronized(lock1) {
                    System.out.println("Thread 1 lock1");
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    synchronized(lock2) {
                        System.out.println("Thread 1 lock2");
                    }
                }
            }
        });
 
        var t2 = new Thread(new Runnable() {
            public void run() {
                synchronized(lock2) {
                    System.out.println("Thread 2 lock2");
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    synchronized(lock1) {
                        System.out.println("Thread 2 lock2");
                    }
                }
            }
        });
 
        t1.start();
        t2.start();

    }
}
