/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jav.mpmc.sample;

import org.junit.Test;

import jav.mpmc.sample.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
