/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dangling.pointer;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) throws Exception {
        // Create an ArrayList and store numbers 1,2,3 in it
        var danglingPointer = new ArrayList<Integer>(5);
        danglingPointer.add(1);
        danglingPointer.add(2);
        danglingPointer.add(3);

        var danglingPointerCopy = danglingPointer;
        danglingPointer = null;
        System.out.println(danglingPointerCopy);
    }
}
